"use client"; 
import { type NextPage } from "next";
import { useState, useEffect, ChangeEvent, MouseEvent } from 'react';
import Image from 'next/image'
import officialLogo from './images/replaymyvidlogo.png'
import Head from 'next/head'
import '../app/styles.css'
const Home: NextPage = () => {
  const [snapchatUrl, setSnapchatUrl] = useState('');
  const [videoUrl, setVideoUrl] = useState<string>('');
  const [iframeSrc, setIframeSrc] = useState<string>('');

  useEffect(() => {
    const fetchSnapchatUrl = async () => { try {
    alert('This is the url: ' + getSnapchatUrl()); 
    const url = await getSnapchatUrl(); 
    if (typeof url === 'string') { 
      setSnapchatUrl(url); 
      alert('Hello, here are your subscribers: ' + url); 
    } 
    else { 
      alert('You failed: ' + url); 
      setSnapchatUrl('Unexpected response from Snapchat URL fetch'); 
    } 
  } catch (error) { 
    console.error('Failed to fetch Snapchat URL:', error); 
    setSnapchatUrl('Failed to fetch Snapchat URL'); 
  } 
};  
    fetchSnapchatUrl();
  }, []);

  const handleInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    setVideoUrl(event.target.value);
  };
  const handleReplayClick = async (event: MouseEvent<HTMLButtonElement>) => {
    // YouTube URL pattern
    const youtubePattern = /(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/;
    // Rumble URL pattern
    //const rumblePattern = /rumble\.com\/v([a-zA-Z0-9_-]+)-/;
    const rumblePattern = /rumble\.com\/(?:v([a-zA-Z0-9_-]+)-|embed\/v([a-zA-Z0-9_-]+)\/)/;
    // Twitter URL pattern
    const twitterPattern = /x\.com\/[a-zA-Z0-9_]+\/status\/(\d+)/;

  if (rumblePattern.test(videoUrl)) {
    /*
    fetch('http://localhost:3000/api/getRumbleUrl') 
    */
   const  response = await fetch('http://localhost:3000/api/getRumbleUrl', {
    method: 'POST',
    headers: {'Content-Type': 'application/json'},
    body: JSON.stringify({url: videoUrl}),
   }) 
   const html = await response.text()
   console.log("This is the Rumble html on the page.tsx: " + html);

    alert('Entered into Rumble')
    return;
  }
  else if (twitterPattern.test(videoUrl)) {
   const response = await fetch('/api/getTwitterUrl', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ url: videoUrl }),
   })
   const html = await response.text();
    console.log("This is the Twitter html on the page.tsx: " + html);
   // fetch('http://localhost:3000/api/getTwitterUrl')
    alert('Entered Twitter')
    return;
  }
  else if (youtubePattern.test(videoUrl)) {
      const videoId = videoUrl.match(youtubePattern)?.[1];      
      if (videoId) {
        const embedUrl = generateEmbedUrl(videoId);
        setIframeSrc(embedUrl);
        return;
      }
      alert('Entered Youtube')
  } 
    setIframeSrc(''); // Clear iframe if URL is not valid
    alert('Link is not valid');
  };
  const getRumbleUrl = async () => {
    fetch('http://localhost:3000/api/getRumbleUrl')
  }
  const generateEmbedUrl = (videoId: string) => {
    return `https://www.youtube.com/embed/${videoId}?loop=1&playlist=${videoId}`;
  }
  const getSnapchatUrl = async () => { 
    try { 
      const response = await fetch('http://localhost:3000/api/getSnapchatUrl'); 
      if (!response.ok) { 
        throw new Error('Failed to fetch Snapchat URL'); 
      } 
      const url = await response.text(); 
      setSnapchatUrl(url); 
      console.log('Hello, here are your subscribers: ' + url); 
    } catch (error) { 
      console.error(error); 
      setSnapchatUrl('Failed to fetch Snapchat URL'); 
    } 
  };
return(
  <div>
    <Head>
      <title>Home</title>
      <meta name='description' content='Generated by Home' />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Image src={officialLogo} className='mx-auto' width={250} height={250} alt="This is the logo of my site." />
    <p className='text-center'>Your Music... No Interruptions</p>
    <div className='flex flex-col items-center mt-8'>
      <form action="">
        <input className='border-solid border-2 border-light-blue-500 h-9 w-96 text-center' type="text" name='link' placeholder='Enter the URL...' value={videoUrl} onChange={handleInputChange} />
      </form>          
      <button type="button" onClick={handleReplayClick} className='p-2 mt-2 bg-red-700 text-center hover:text-red-600 hover:bg-white hover:border-2 hover:border-red-600 font-serif rounded text-sm text-white'>REPLAY</button>
      {iframeSrc && (
        <iframe className='mt-1 iframe-video' width="640" height="360" src={iframeSrc} allowFullScreen title="Video player"/>
      )}
    </div>
    <p className='text-center mt-10'>Watch your favorite YouTube, X (Formerly known as Twitter), or Rumble video over and over again without pressing replay (:</p>
    {/*<
    <div className="flex mt-20 w-screen items-center justify-center">
      <input type="text" className="rounded-md border-2 border-gray-300 p-2" placeholder="Enter Rumble URL"/>
      <button onClick={getSnapchatUrl} type="button" className="rounded-md big-pink-600 p-4 text-xl font-bold">Enter</button>
     blockquote className="twitter-tweet" data-media-max-width="560"><p lang="en" dir="ltr">6 days until Vultures <a href="https://t.co/oIht49i7lv">pic.twitter.com/oIht49i7lv</a></p>&mdash; Donda Times (@dondatimes) <a href="https://twitter.com/dondatimes/status/1753797053019308420?ref_src=twsrc%5Etfw">February 3, 2024</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charSet="utf-8"></script> 
    </div>      
    <p className="text-center">This is just used for testing at the moment</p> */} 
      <p className='text-center mt-4'>Here are your subscribers: {snapchatUrl}</p>
  </div>
)
}

export default Home