"use client"; 
import { type NextPage } from "next";
import { useState, ChangeEvent, MouseEvent } from 'react';
import Image from 'next/image'
import logo from './images/logo.png'
import Head from 'next/head'

const Home: NextPage = () => {

  const [videoUrl, setVideoUrl] = useState<string>('');
  const [iframeSrc, setIframeSrc] = useState<string>('');

  const handleInputChange = (event: ChangeEvent<HTMLInputElement>) => {
    setVideoUrl(event.target.value);
  };
  const handleReplayClick = async (event: MouseEvent<HTMLButtonElement>) => {
    // YouTube URL pattern
    const youtubePattern = /(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/;
    // Rumble URL pattern
    //const rumblePattern = /rumble\.com\/v([a-zA-Z0-9_-]+)-/;
    const rumblePattern = /rumble\.com\/(?:v([a-zA-Z0-9_-]+)-|embed\/v([a-zA-Z0-9_-]+)\/)/;
    // Twitter URL pattern
    const twitterPattern = /x.com\.\/v([a-zA-z0-9_-]+)-/;

  if (rumblePattern.test(videoUrl)) {

  }
  else if (twitterPattern.test(videoUrl)) {

  }
  else if (youtubePattern.test(videoUrl)) {
      const videoId = videoUrl.match(youtubePattern)?.[1];      
      if (videoId) {
        const embedUrl = generateEmbedUrl(videoId);
        setIframeSrc(embedUrl);
        return;
      }
  } 
    setIframeSrc(''); // Clear iframe if URL is not valid
    alert('Link is not valid');
  };
  const getRumbleUrl = async () => {
    fetch('http://localhost:3001/api/getRumbleUrl')
  }
  const generateEmbedUrl = (videoId: string) => {
    return `https://www.youtube.com/embed/${videoId}?loop=1&playlist=${videoId}`;
  }
return(
  <>
    <Head>
      <title>Home</title>
      <meta name='description' content='Generated by Home' />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Image src={logo} className='mx-auto' width={250} height={250} alt="This is the logo of my site." />
    <div className="flex h-screen w-screen items-center justify-center">
      <input type="text" className="rounded-md border-2 border-gray-300 p-2" placeholder="Enter Rumble URL"/>
      <button onClick={getRumbleUrl} type="button" className="rounded-md big-pink-600 p-4 text-xl font-bold">Enter</button>
     {/*<blockquote className="twitter-tweet" data-media-max-width="560"><p lang="en" dir="ltr">6 days until Vultures <a href="https://t.co/oIht49i7lv">pic.twitter.com/oIht49i7lv</a></p>&mdash; Donda Times (@dondatimes) <a href="https://twitter.com/dondatimes/status/1753797053019308420?ref_src=twsrc%5Etfw">February 3, 2024</a></blockquote> <script async src="https://platform.twitter.com/widgets.js" charSet="utf-8"></script> */} 
    </div>
  </>
)
}

export default Home